site_name: Prealignment
nav:
  - Introduction: intro.md
  - Softwares: softwares.md
  - Rule graph: rule_graph.md

theme: readthedocs
extra_css: [extra.css]
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
      base_path: ["docs"]
  - mdx_spanner

plugins:
  - yaml-schema:
       yaml_files:
         - file: "workflow/schemas/config.schema.yaml"
           tag: "CONFIGSCHEMA"
         - file: "workflow/schemas/resources.schema.yaml"
           tag: "RESOURCESSCHEMA"
  - snakemake-rule:
      rule_folders:
        - 'workflow/rules'