site_name: Prealignment
nav:
  - Introduction: index.md
  - Softwares: softwares.md
  - Rule graph: rule_graph.md

theme: readthedocs
extra_css: [extra.css]
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
      base_path: ["docs"]
  - mdx_spanner
