$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:
  samples:
    type: string
  units:
    type: string
  containers:
    type: object
    properties:
      common:
        type: string
    required:
      - common
  required:
    - samples
    - units
    - containers
