name: small integration test

on:
  push:
    branches:
     - develop
     - master
  workflow_dispatch:

jobs:
  integration-small-conda:
    name: integration small data set conda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Add conda to system path
        run: |
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          conda config --set channel_priority strict
          conda install -c conda-forge mamba=0.15.3
      - name: Install requirements.txt
        run: |
          pip install -r requirements.txt
      - name: Install requirements.test.txt
        run: |
          pip install -r requirements.test.txt
      - name: Integration test merge config, conda
        working-directory: .tests/integration
        run: |
          snakemake --cores 2 -s ../../workflow/Snakefile -j 2 --show-failed-logs --configfile config.yaml --use-conda && rm -r prealignment
      - name: Integration test fastp_merge config, conda
        working-directory: .tests/integration
        run: |
          snakemake --cores 2 -s ../../workflow/Snakefile -j 2 --show-failed-logs --configfiles config.yaml configs/fastp_merge_config.yaml --use-conda && rm -r prealignment
  integration-small-singularity:
    name: integration small data set singularity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Add conda to system path
        run: |
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          conda config --set channel_priority strict
          conda install -c conda-forge mamba=0.15.3
      - name: Install requirements.txt
        run: |
          pip install -r requirements.txt
      - name: Install requirements.test.txt
        run: |
          pip install -r requirements.test.txt
      - name: Install singularity
        run: |
          mamba install -c conda-forge -c bioconda singularity=3.8.6
      - name: Integration test merge config, singularity
        working-directory: .tests/integration
        run: |
          snakemake --cores 2 -s ../../workflow/Snakefile -j 2 --show-failed-logs --configfiles config.yaml --use-singularity --singularity-args  " --cleanenv --bind /home/runner " && rm -r prealignment
      - name: Integration test fastp_merge config, singularity
        working-directory: .tests/integration
        run: |
          snakemake --cores 2 -s ../../workflow/Snakefile -j 2 --show-failed-logs --configfiles config.yaml configs/fastp_merge_config.yaml --use-singularity --singularity-args  " --cleanenv --bind /home/runner " && rm -r prealignment
