name: small integration test

on:
  push:
    branches:
     - develop
     - master
  workflow_dispatch:

jobs:
  integration-small-singularity:
    name: integration small data set singularity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniforge-variant: Mambaforge
            miniforge-version: latest
            activate-environment: my-env
            use-mamba: true
      - name: Set strict channel
        run: |
          conda config --set channel_priority strict
          mamba install -c conda-forge -c bioconda apptainer=1.3.2
      - name: Install requirements.txt
        run: |
          pip install -r requirements.txt
      - name: Install requirements.test.txt
        run: |
          pip install -r requirements.test.txt
      - name: Add conda to system path
        run: |
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Integration test merge config, singularity
        working-directory: .tests/integration
        run: |
          snakemake --cores 2 -s ../../workflow/Snakefile -j 2 --show-failed-logs --configfiles config.yaml --use-singularity --singularity-args  " --cleanenv --bind /home/runner " && rm -r prealignment
      - name: Integration test fastp_merge config, singularity
        working-directory: .tests/integration
        run: |
          snakemake --cores 2 -s ../../workflow/Snakefile -j 2 --show-failed-logs --configfiles config.yaml configs/fastp_merge_config.yaml --use-singularity --singularity-args  " --cleanenv --bind /home/runner " && rm -r prealignment
      - name: Integration test pacbio config, singularity
        working-directory: .tests/integration
        run: |
          snakemake --cores 2 -s ../../workflow/Snakefile -j 2 --show-failed-logs --configfiles config_pacbio.yaml  --use-singularity --singularity-args  " --cleanenv --bind /home/runner " && rm -r prealignment
