name: Lint and Test

# Controls when the action will run.
on:
   # Triggers the workflow on push or pull request events but only for the master and develop branch
  push:
    branches:
     - develop
     - master
  pull_request:
    branches:
     - develop
     - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    name: Lint workflow
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Linting
        uses: snakemake/snakemake-github-action@v1.22.0
        with:
          directory: ".tests/integration"
          snakefile: "workflow/Snakefile"
          args: "--lint"
  snakefmt:
    name: Snakefmt
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_SNAKEMAKE_SNAKEFMT: true
          OUTPUT_FOLDER: .github/linters/report
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Add conda to system path
        run: |
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          conda install -c conda-forge mamba
      - name: Install requirements.txt
        run: |
          pip install -r requirements.txt
      - name: Install requirements.test.txt
        run: |
          pip install -r requirements.test.txt
      - name: Check python syntax lib
        run: pycodestyle --max-line-length=130 --statistics workflow/scripts
      - name: pytest
        run: pytest workflow/scripts
  snakemake:
    name: Run snakemake commands
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Add conda to system path
        run: |
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          conda install -c conda-forge mamba
      - name: Install requirements.txt
        run: |
          pip install -r requirements.txt
      - name: Install requirements.test.txt
        run: |
          pip install -r requirements.test.txt
      - name: Check python syntax lib
        run: pycodestyle --max-line-length=130 --statistics workflow/scripts
      - name: pytest
        run: pytest workflow/scripts
      - name: Integration test - dry-run
        working-directory: .tests/integration
        run: |
          mamba install -c conda-forge -c bioconda snakemake singularity
          snakemake -n -s ../../workflow/Snakefile
      - name: Integration test
        working-directory: .tests/integration
        run: |
          mamba install -c conda-forge -c bioconda snakemake singularity
          snakemake -s ../../workflow/Snakefile -j 1 --use-singularity
